.PHONY: clean All

All:
	@echo "----------Building project:[ Perceptron - Debug ]----------"
	@$(MAKE) -f  "Perceptron.mk"
clean:
	@echo "----------Cleaning project:[ Perceptron - Debug ]----------"
	@$(MAKE) -f  "Perceptron.mk" clean
